### ISSUE TITLE
Location Menu is not displayed when there are just CSS files in frames

### ISSUE THREAD

**Issue by sdavidg** [firebug/firebug.next#291] opened 2015-01-22 11:06 UTC
The same error that appeared here:  https://code.google.com/p/fbug/issues/detail?id=6531

**Comment by janodvarko** [comment] 2015-01-23 14:51
I don't understand the reported bug. The test case is online here:
https://getfirebug.com/tests/1.12/css/6531/issue6531.html

and there is only one embedded stylesheet inside issue6531-iframe.html

I can see the stylesheet in the list of stylesheets at the left side of the Style Editor panel.

See my screenshot

![291](https://cloud.githubusercontent.com/assets/37785/5876471/b3c5327c-a317-11e4-93a6-4a8f53308d8e.png)

Honza

**Comment by sdavidg** [comment] 2015-01-23 16:16
I guess the frames and iframes are slightly different

FB 3a7
![untitled](https://cloud.githubusercontent.com/assets/4955944/5877927/52507c3e-a323-11e4-9c07-83a348c4ebf2.png)

-----------------------
FB 2.0.7
![untitled2](https://cloud.githubusercontent.com/assets/4955944/5877928/5253fcba-a323-11e4-9ed8-c4e491271f2f.png)

**Comment by fflorent** [comment] 2015-01-23 20:28
@sdavidg Yeah, I could reproduce your issue. Thanks for the report! 
Actually, it is a DevTools's one. Could you report an issue in bugzilla? (looks like [it is not reported](https://bugzilla.mozilla.org/buglist.cgi?list_id=11903762&short_desc=frame&resolution=---&query_format=advanced&short_desc_type=allwordssubstr&component=Developer%20Tools%3A%20Style%20Editor))

Otherwise, a workaround is to go to the Firebug options, in the "Available Options" section check the "Select an iframe as [...]" option and refresh. Then you can select a frame going to "Tools" > "Select an iframe [...]".

Florent

**Comment by janodvarko** [comment] 2015-11-19 16:13
As @fflorent  said, it would be great to have Bugzilla bug.
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Developer%20Tools%3A%20Style%20Editor

Closing
Honza

**Closed by janodvarko** 2015-11-19 16:13 UTC
Labels: platform, style editor
